Fix sqlline by removing redundant slf4j dependency (log4j-over-slf4j) from cassandra-all
SLF4J initialization was failing due to `NoClassDefFoundError`.